[project]
name = "langchain-pgvector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.20",
    "langchain-openai>=0.3.9",
    "langchain-postgres>=0.0.13",
]
